### ISSUE TITLE
Whatsapp icon dissappeared in flutter 3.7

### ISSUE THREAD

**Issue by nicolaspernoud** [Ahmadre/FlutterIconPicker#53]
Hello,
After upgrading to flutter 3.7, i get the following error : flutter_iconpicker-3.2.2/lib/IconPicker/Packs/Material.dart:25632:21: Error: Member not found: 'whatsapp'.
It seems that icon does not exist anymore !?

**Comment by flutterWithChris** [comment]
Just created a PR that fixes this issue. Hoping it gets reviewed & merged soon!

**Comment by HusseinM11** [comment]
Facing the same issue, hope it gets fixed soon.

**Comment by CharlesLim0721** [comment]
> Just created a PR that fixes this issue. Hoping it gets reviewed & merged soon!

Thanks flutterWithChris 👍🏻

**Comment by razfazz** [comment]
same issue

**Comment by azimuthdeveloper** [comment]
You can use @CharlesLim0721's fix today without waiting for a PR by putting this in your `pubspec.yaml`. Just remember to change it later.

```
  flutter_iconpicker:
    git:
      url: https://github.com/kechankrisna/FlutterIconPicker
      ref: hotfix
```
